### PR TITLE
Event Dispatcher

### PR DESCRIPTION
**Pull request by jrdnhannah**
Correct the event dispatcher tests to reflect the new Smooth PHP event dispatcher

### CODE REVIEW

**Comment by mrsimonbennett** [comment]
@jrdnhannah what happened to travis?

**Comment by jrdnhannah** [comment]
That's a good question.......

**Comment by mrsimonbennett** [comment]
What happened to the travis file haha

**Comment by mrsimonbennett** [comment]
Not sure if i am going to bung tests in the laravel one at the moment. To really much to test

**Comment by jrdnhannah** [comment]
Ha turns out it was empty. Just about to make PR. Not testing everything in SF just the container compiling.

**Comment by jrdnhannah** [comment]
Wait till I PR the new travis stuff, I'll merge into here and hopefully travis will run all smiles and shit

**Pull request merged**
